(function($){var widgetSlideup=function($scope,$){let animationDuration;if($scope.hasClass('coherence-slideup-entrance-animation-sl')){$scope.removeClass('coherence-slideup-entrance-animation-sl').addClass('coherence-slideup-entrance-animation-fade')}else if($scope.hasClass('coherence-slideup-entrance-animation-gr')){$scope.removeClass('coherence-slideup-entrance-animation-gr').addClass('coherence-slideup-entrance-animation-fade')}
if($scope.hasClass('coherence-slideup-entrance-type-ps')){$scope.removeClass('coherence-slideup-entrance-type-ps').addClass('coherence-slideup-entrance-type-cover')}
function openSlideup(slideupSelector){animationDuration=+slideupSelector.find('.coherence-slideup-content').css('animation-duration').replace('s','')*1000;slideupSelector.fadeIn(animationDuration);slideupSelector.addClass('coherence-slideup-wrap-active');if($scope.hasClass('coherence-slideup-entrance-animation-slide')){if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-slide-in')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-slide-in').addClass('coherence-slideup-slide-out')}else{slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-slide-out').addClass('coherence-slideup-slide-in')}}else if($scope.hasClass('coherence-slideup-entrance-animation-grow')){if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-grow-in')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-grow-in').addClass('coherence-slideup-grow-out')}else{slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-grow-out').addClass('coherence-slideup-grow-in')}}else if($scope.hasClass('coherence-slideup-entrance-animation-fade')){if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-fade-in')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-fade-in').addClass('coherence-slideup-fade-out')}else{slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-fade-out').addClass('coherence-slideup-fade-in')}}
$(window).trigger('resize')}
function closeSlideup(slideupSelector){if($scope.hasClass('coherence-slideup-entrance-animation-slide')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-slide-in').addClass('coherence-slideup-slide-out')}else if($scope.hasClass('coherence-slideup-entrance-animation-grow')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-grow-in').addClass('coherence-slideup-grow-out')}else if($scope.hasClass('coherence-slideup-entrance-animation-fade')){slideupSelector.find('.coherence-slideup-content').removeClass('coherence-slideup-fade-in').addClass('coherence-slideup-fade-out')}
slideupSelector.fadeOut(animationDuration);slideupSelector.removeClass('coherence-slideup-wrap-active')}
if($scope.hasClass('coherence-slideup-entrance-type-push')){function growBodyWidth(){openSlideup(slideupSelector);$('body').addClass('coherence-slideup-body-overflow');if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-left')){bodyInnerWrap.animate({'margin-left':slideupSelector.find('.coherence-slideup-content').width()+'px'},'slow');bodyInnerWrap.css({'transition-duration':slideupSelector.find('.coherence-slideup-content').css('animation-duration'),'transform':'translateX('+slideupSelector.find('.coherence-slideup-content').outerWidth()+'px)',})}else if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-right')){bodyInnerWrap.animate({'margin-right':slideupSelector.find('.coherence-slideup-content').width()+'px'},'slow');bodyInnerWrap.css({'transition-duration':slideupSelector.find('.coherence-slideup-content').css('animation-duration'),'transform':'translateX(-'+slideupSelector.find('.coherence-slideup-content').outerWidth()+'px)',})}else if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-top')){bodyInnerWrap.animate({'margin-top':slideupSelector.find('.coherence-slideup-content').outerHeight()+'px'},'slow');bodyInnerWrap.css({'transition-duration':slideupSelector.find('.coherence-slideup-content').css('animation-duration'),'margin-top':slideupSelector.find('.coherence-slideup-content').outerHeight()+'px',})}}
function reduceBodyWidth(){closeSlideup(slideupSelector);if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-left')){bodyInnerWrap.animate({'margin-left':0},'slow');bodyInnerWrap.css({'transform':'translateX(0px)'})}else if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-right')){bodyInnerWrap.animate({'margin-right':0},'slow');bodyInnerWrap.css({'transform':'translateX(0px)'})}else if(slideupSelector.find('.coherence-slideup-content').hasClass('coherence-slideup-content-top')){bodyInnerWrap.animate({'margin-top':0},'slow');bodyInnerWrap.css({'margin-top':0})}
$('body').removeClass('coherence-slideup-body-overflow')}
function closeTriggers(){slideupSelector.on('click',function(e){if(!e.target.classList.value.includes('coherence-slideup-content')&&!e.target.closest('.coherence-slideup-content')){reduceBodyWidth()}});$(document).on('keyup',function(event){if(event.key=="Escape"){reduceBodyWidth()}});slideupSelector.find('.coherence-close-slideup').on('click',function(){reduceBodyWidth()})}
if(!($('.coherence-slideup-body-inner-wrap-'+$scope.data('id')).length>0)){$("body").wrapInner('<div class="coherence-slideup-body-inner-wrap-'+$scope.data('id')+'" />')}
var bodyInnerWrap=$('.coherence-slideup-body-inner-wrap-'+$scope.data('id'));bodyInnerWrap.css('position','relative');if(!(bodyInnerWrap.prev('.coherence-slideup-wrap').length>0)){$scope.find('.coherence-slideup-wrap').addClass('coherence-slideup-wrap-'+$scope.data('id'));document.querySelector('body').insertBefore($scope.find('.coherence-slideup-wrap')[0],document.querySelector('.coherence-slideup-body-inner-wrap-'+$scope.data('id')))}
var slideupSelector=$('.coherence-slideup-wrap-'+$scope.data('id'));$scope.find('.coherence-slideup-trigger').on('click',function(){if($('.coherence-slideup-wrap-'+$scope.data('id')).length>0&&$scope.find('.coherence-slideup-wrap').length>0){$('.coherence-slideup-wrap-'+$scope.data('id')).remove();$scope.find('.coherence-slideup-wrap').addClass('coherence-slideup-wrap-'+$scope.data('id'));document.querySelector('body').insertBefore($scope.find('.coherence-slideup-wrap')[0],document.querySelector('.coherence-slideup-body-inner-wrap-'+$scope.data('id')));slideupSelector=$('.coherence-slideup-wrap-'+$scope.data('id'))}
if(slideupSelector.hasClass('coherence-slideup-wrap-active')){reduceBodyWidth()}else{growBodyWidth()}});if('yes'===$scope.find('.coherence-slideup-container').data('slideup-open')){$scope.find('.coherence-slideup-trigger').trigger('click')}
closeTriggers();var mutationObserver=new MutationObserver(function(mutations){closeTriggers()});mutationObserver.observe($scope[0],{childList:!0,subtree:!0,})}else{$scope.find('.coherence-slideup-trigger').on('click',function(){openSlideup($scope.find('.coherence-slideup-wrap'))});$scope.find('.coherence-slideup-wrap').on('click',function(e){if(!e.target.classList.value.includes('coherence-slideup-content')&&!e.target.closest('.coherence-slideup-content')){closeSlideup($scope.find('.coherence-slideup-wrap'))}});if('yes'===$scope.find('.coherence-slideup-container').data('slideup-open')){$scope.find('.coherence-slideup-trigger').trigger('click')}
$(document).on('keyup',function(event){if(event.key=="Escape"){closeSlideup($scope.find('.coherence-slideup-wrap'))}});$scope.find('.coherence-close-slideup').on('click',function(){closeSlideup($scope.find('.coherence-slideup-wrap'))})}}
$(window).on('elementor/frontend/init',function(){elementorFrontend.hooks.addAction('frontend/element_ready/slideup.default',widgetSlideup)})})(jQuery)